// Generated by rulesync. Do not edit manually.
import { exec } from "node:child_process";
import { promisify } from "node:util";

import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";

const run = promisify(exec);

function toBlockReason(error: unknown): string {
  const result = error as { stdout?: unknown; stderr?: unknown; code?: unknown } | null;
  const stderr = String(result?.stderr ?? "").trim();
  if (stderr) return stderr;
  const stdout = String(result?.stdout ?? "").trim();
  if (stdout) return stdout;
  if (result?.code !== undefined) return `Hook command failed with exit code ${result.code}.`;
  return error instanceof Error ? error.message : String(error);
}

export default function (pi: ExtensionAPI) {
  pi.on("tool_call", async (event) => {
    if (new RegExp("Bash").test(event.toolName)) {
      try {
        await run(".rulesync/hooks/security-guard.sh");
      } catch (error) {
        return { block: true, reason: toBlockReason(error) };
      }
    }
  });
}
